name: git-flags
description: Sets git-clone and git-fetch flags
author: https://github.com/whizzzkid
requirements: ['git']
configuration:
  properties:
    clone_flags:
      type: string
    fetch_flags:
      type: string
  required: []
